### ISSUE TITLE
Unable to submit payment with given values

### ISSUE THREAD

**Issue by st0rmr1der1994** [bun4uk/currency#1]
Trying to submit payment with following data 

![image](https://cloud.githubusercontent.com/assets/9132561/24353890/75d29bfa-12f8-11e7-89ef-21b96071bf40.png)

Receiving error:
`Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.`

**8=======Э**

**Comment by bun4uk** [comment]
Dude, thanks for your feedback! 
Will be fixed soon.
凸( ͡° ͜ʖ ͡°)凸

**Comment by bun4uk** [comment]
https://github.com/bun4uk/currency/commit/7338993c3dabcbe6d2ba25cecf062209c9d91936
Added error handling during bank api calls.

**Comment by st0rmr1der1994** [comment]
Roger that
