### ISSUE TITLE
The selected item isn't visible

### ISSUE THREAD

**Issue by KateNegrienko** [bun4uk/currency#2]
http://prntscr.com/epg4k7

**Comment by bun4uk** [comment]
Kate, thanks for your feedback! I'll fix it asap.
Good luck! :)

**Comment by bun4uk** [comment]
@KateNegrienko Done!
![image](https://cloud.githubusercontent.com/assets/14631690/24445394/6bc8a4b2-1472-11e7-9383-763b97fc7af5.png)
