### ISSUE TITLE
Show amount in Грн 

### ISSUE THREAD

**Issue by KateNegrienko** [bun4uk/currency#4]

**Comment by bun4uk** [comment]
@KateNegrienko, can you pls describe this issue more clearly?
Thanks!

**Comment by bun4uk** [comment]
@KateNegrienko All new payments will store full amount of hrn from now
![image](https://cloud.githubusercontent.com/assets/14631690/24541031/716d0f1a-15fe-11e7-8bd6-a13325b1bebe.png)
