### ISSUE TITLE
Negative numbers calc

### ISSUE THREAD

**Issue by groovili** [bun4uk/currency#7]
When income is negative script adds it to whole sum.
So we can get negative income and tax.
Date in future or in past gives error saying that bank data are not available, maybe better limit calendar to dates you can process?

**Comment by bun4uk** [comment]
Bug with negative sums are fixed. Now form has assertions that incoming value should be greater than or equal to 0.

As for bank availability error - i'm planning to limit calendar in future. 
Created a new issue https://github.com/bun4uk/currency/issues/8

Thanks!
